name: marketplace
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Sf Pro
      fonts:
        - asset: assets/fonts/sf_pro_bold.OTF
        - asset: assets/fonts/sf_pro_medium.OTF
        - asset: assets/fonts/sf_pro_regular.OTF
        - asset: assets/fonts/sf_pro_semi_bold.ttf

    #         style: italic
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/roboto/roboto_regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

